### ISSUE TITLE
Push the initial files to the master branch

### ISSUE THREAD

**Issue by og2t** [hermitsoft/jsSID#1]
Hi Hermit! Here's Digger/ESM. Nice to see the repo :) Now you just need to commit and push all the jsSID files to the repository. Thanks!

**Comment by hermitsoft** [comment]
Hi Digger

This github page is awesome, much better than SourceForge. Why the hell I haven't tried it yet, dunno... (Maybe simply because I was not familiar with git, just svn...)

The jsSID files are coming today...(I just need to install git commandline on my system...)

First I need to mention that I have no much long-term plans at the moment for jsSID.
It is what it is... But if You or other people want to improve it, I don't stand in the way...
What more, I'm glad if there is such interest and evolution in this projet.
Eventually CSDB/HVSC and other SID-hosting sites could include buttons to play the SIDs directly in browser to enhance visitors' experience, especially new users not familiar with SID players and emulators.
(But that would require full CIA/VIC environment emulation which I didn't plan for in the 1st place... That's really necessary to play all tunes, including digis...)
The 'goal', whatsoever, is to keep it small and fast, but retain sound quality.
Though this is not a strict goal, as I mention in the README, do what you want with this code... :)
Of course if help needed I'm here... Maybe my initial code is not so readable for some people...
(And maybe comments are scarce. If needed I could explain how I made high pitched pulse/saw sounds clean, and how the combined waveforms are working in the SID according to my examinations.)
If digis come into play, I have a solution already to them, I even worked out a solution recently to avoid distortion of synth+digi SIDs like Turbo Outrun: $d418 low-pass filtered DC component goes to volume setting, high-pass filtered AC component goes to 'digi channel'... That eliminates the digi boost volume setting clicks as well, as only the DC component goes to the volume. Hades Nebula and similar fade-in/out tunes benefit from this solution...)

**Comment by og2t** [comment]
Thanks for reply Hermit :) I can help you out with GIT if you want – it's a superior replacement for SVN and the GitHub community is fantastic. No long-term plans for jsSID is fine too, you've planted a gold seed, now you'll see how it grows.

First of all, I was totally impressed with your skills and this minimalistic and concise implementation that actually works as charm!

I am particularly interested in adding waveform monitors (like this https://www.youtube.com/watch?v=G1AeBgalFZk) and interactive memory monitor (like this http://play.blog2t.net/flash-as3-c64-intro-previewer/) – these are not needed features at all, but it excites me to see what's happening on the low level in realtime :)

Another idea I've had was to create browser based interactive SID composer that wouldn't use 6502 but just your SID emulation (because it's so good).

Few suggestions I'd like to have and can do:
1. Split the modules (SID, CPU, Player, Playlist) into individual .js files, so they can be used individually  
2. Format the source code, so there's more breathing space for comments
3. Improve CSS styling for the demo page and player
4. Someone could implement the CIA/VIC timers etc.

Look forward to working on these points!

**Comment by hermitsoft** [comment]
Great to hear you want to contribute. I usually code compact codes. I know it's not the trend  or what they teach, but this works for me better than opening and handling many source files and scrolling-scrolling-scrolling to get to a part of a code. As this code fits only 300 rows in a single file this way, it's easy to handle, but I can understand it's not good for open-source development and commenting. To keep my formatting intact for at least the initial commit, I'll leave it like this, then it's up to you and the community to make it feel better for contribution...splitting files, editing, whatever, I'll give any permission if I get asked for it...
(When I develop software versions I try to retain phases, and I usually commit/archive working phases/milestones. Maybe that's the practice for many others. So I'll upload 0.9 first with single-SID support, then commit 0.9.1 onto it, then upcoming phases - CSS beautification, CIA/VIC emulation, etc. - can follow..)

The idea about the debugger is good. Yesterday a guy just asked me for this thing, so I'm looking forward your implementation. It can be a power SID-debugger/learn-tool with human-centric SID register-modification displays, playmarks, ffwd/rewind functions, etc...)

**Comment by hermitsoft** [comment]
I uploaded the files gradually, and made the source/jsSID.js more readable with many comments to help further development. Good luck, and if anyone want to join the project drop me a message to give permissions (I guess it's done like that here too at GitHub)...

**Comment by og2t** [comment]
Hi Hermit, can you set me up as a maintainer of your repo too? Thx.

**Comment by hermitsoft** [comment]
Sorry for the late answer, I was abroad for 2 weeks, different activities took my time...
I added you as a collaborator for jsSID main branch.  
Tell me if I still should give some more permissions somewhere..

**Comment by og2t** [comment]
Thanks Hermit! Busy times! So far I've improved the docs styling and I am planning to add an online HVSC player in React.js – will see how it goes.
